"""Add columns birthdate and description

Revision ID: 1c1954515e9d
Revises: fd0e0f797d15
Create Date: 2025-01-09 22:10:26.599289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c1954515e9d'
down_revision: Union[str, None] = 'fd0e0f797d15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scientist', sa.Column('birthdate', sa.Date(), nullable=True))
    op.add_column('conference', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scientist', 'birthdate')
    op.drop_column('conference', 'description')
    # ### end Alembic commands ###
