"""Add indexes

Revision ID: 38236d1de5a2
Revises: 1c1954515e9d
Create Date: 2025-01-09 22:15:30.328682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38236d1de5a2'
down_revision: Union[str, None] = '1c1954515e9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_conference_topic', 'conference', ['topic'], unique=False)
    op.create_index('ix_participation_scientist_conference', 'participation', ['scientist_id', 'conference_id'],
                    unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_conference_topic', table_name='conference')
    op.drop_index('ix_participation_scientist_conference', table_name='participation')

# ### end Alembic commands ###
