""" add_json_tags_field_to_conference_table

Revision ID: d806cde909e3
Revises: bdf088ad04f8
Create Date: 2025-01-09 23:46:59.375965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd806cde909e3'
down_revision: Union[str, None] = 'bdf088ad04f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_conference_topic', table_name='conference')
    op.drop_column('conference', 'description')
    op.drop_column('conference', 'tags')
    op.drop_index('ix_participation_scientist_conference', table_name='participation')
    op.drop_column('scientist', 'birthdate')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scientist', sa.Column('birthdate', sa.DATE(), autoincrement=False, nullable=True))
    op.create_index('ix_participation_scientist_conference', 'participation', ['scientist_id', 'conference_id'], unique=False)
    op.add_column('conference', sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('conference', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index('ix_conference_topic', 'conference', ['topic'], unique=False)
    # ### end Alembic commands ###
