"""Initial migration

Revision ID: fd0e0f797d15
Revises: 
Create Date: 2025-01-04 22:40:50.086867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd0e0f797d15'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scientist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_surname', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('scientific_degree', sa.String(length=50), nullable=False),
    sa.Column('organization', sa.String(length=100), nullable=True),
    sa.Column('specialization', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scientist_id', sa.Integer(), nullable=False),
    sa.Column('conference_id', sa.Integer(), nullable=False),
    sa.Column('report_theme', sa.String(length=100), nullable=False),
    sa.Column('performance_duration', sa.Time(), nullable=False),
    sa.Column('participation_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['conference_id'], ['conference.id'], ),
    sa.ForeignKeyConstraint(['scientist_id'], ['scientist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participation')
    op.drop_table('scientist')
    op.drop_table('conference')
    # ### end Alembic commands ###
